const PDFDocument = require("pdfkit");
const path = require("path");

const logoPath = path.join(
  __dirname,
  "../assets/invoiceflow-logo.png"
);

// Common PDF content
const buildInvoicePdf = (doc, invoice) => {
  // Logo
  try {
    doc.image(logoPath, 50, 40, {
      width: 180
    });
  } catch (error) {
    console.log("Logo could not be loaded:", error.message);
  }

  // Invoice title
  doc
    .fontSize(24)
    .font("Helvetica-Bold")
    .text("INVOICE", 400, 60, {
      align: "right"
    });

  doc.moveDown(3);

  // Invoice information
  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .text(
      `Invoice Number: ${invoice.invoiceNumber}`
    );

  doc
    .font("Helvetica")
    .text(
      `Issue Date: ${new Date(
        invoice.issueDate
      ).toLocaleDateString()}`
    )
    .text(
      `Due Date: ${new Date(
        invoice.dueDate
      ).toLocaleDateString()}`
    )
    .text(`Status: ${invoice.status}`);

  doc.moveDown();

  // Bill To
  doc
    .font("Helvetica-Bold")
    .text("Bill To:");

  doc
    .font("Helvetica")
    .text(invoice.client.name)
    .text(invoice.client.companyName || "")
    .text(invoice.client.email || "")
    .text(invoice.client.phone || "")
    .text(invoice.client.billingAddress || "");

  doc.moveDown();

  // Invoice Items
  doc
    .font("Helvetica-Bold")
    .text("Invoice Items");

  doc.moveDown();

  // Table header
  const tableY = doc.y;

  doc
    .font("Helvetica-Bold")
    .text("Description", 50, tableY);

  doc.text("Qty", 300, tableY);
  doc.text("Rate", 360, tableY);
  doc.text("Amount", 440, tableY);

  doc.moveDown();

  doc.font("Helvetica");

  // Items
  invoice.items.forEach((item) => {
    const y = doc.y;

    doc.text(
      item.description,
      50,
      y,
      {
        width: 230
      }
    );

    doc.text(
      item.quantity.toString(),
      300,
      y
    );

    doc.text(
      `Rs. ${item.rate.toFixed(2)}`,
      360,
      y
    );

    doc.text(
      `Rs. ${item.amount.toFixed(2)}`,
      440,
      y
    );

    doc.moveDown();
  });

  doc.moveDown();

  // Summary
  doc
    .font("Helvetica-Bold")
    .text(
      `Subtotal: Rs. ${invoice.subtotal.toFixed(
        2
      )}`,
      {
        align: "right"
      }
    );

  doc
    .font("Helvetica")
    .text(
      `Tax (${invoice.taxPercentage}%): Rs. ${invoice.taxAmount.toFixed(
        2
      )}`,
      {
        align: "right"
      }
    );

  doc.text(
    `Discount: Rs. ${invoice.discount.toFixed(
      2
    )}`,
    {
      align: "right"
    }
  );

  doc.moveDown();

  // Grand total
  doc
    .font("Helvetica-Bold")
    .fontSize(14)
    .text(
      `Grand Total: Rs. ${invoice.totalAmount.toFixed(
        2
      )}`,
      {
        align: "right"
      }
    );

  doc.moveDown(2);

  // Footer
  doc
    .fontSize(10)
    .font("Helvetica")
    .text(
      "Thank you for your business.",
      {
        align: "center"
      }
    );

  doc
    .fontSize(8)
    .fillColor("gray")
    .text(
      "Generated by InvoiceFlow",
      {
        align: "center"
      }
    );
};


// Generate PDF Buffer
const generateInvoicePdfBuffer = (
  invoice
) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 50,
      size: "A4"
    });

    const chunks = [];

    doc.on("data", (chunk) => {
      chunks.push(chunk);
    });

    doc.on("end", () => {
      resolve(
        Buffer.concat(chunks)
      );
    });

    doc.on("error", reject);

    buildInvoicePdf(
      doc,
      invoice
    );

    doc.end();
  });
};


// Generate PDF response
const generateInvoicePdf = (
  invoice,
  res
) => {
  const doc = new PDFDocument({
    margin: 50,
    size: "A4"
  });

  res.setHeader(
    "Content-Type",
    "application/pdf"
  );

  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${invoice.invoiceNumber}.pdf`
  );

  doc.pipe(res);

  buildInvoicePdf(
    doc,
    invoice
  );

  doc.end();
};


module.exports = {
  generateInvoicePdf,
  generateInvoicePdfBuffer
};